version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: iamdefault
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: logos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
